const projects = [
  {
    id: 1,
    imageSrc: "/images/projects/eCafe/1.png",
    title: "eCafé",
    description: "Online store to order eatables for a local café",
  },
  {
    id: 2,
    imageSrc: "/images/projects/statistics-app/1.png",
    title: "Project 2",
    description: "Description for Project 2",
  },
  {
    id: 3,
    imageSrc: "/images/projects/eCafe/1.png",
    title: "Project 3",
    description: "Description for Project 3",
  },
];

const details = [
  {
    id: 1,
    technologies: [
      { name: "Java", image: "/images/technologies/java.png" },
      { name: "SpringBoot", image: "/images/technologies/spring-boot.png" },
      { name: "Thymeleaf", image: "/images/technologies/thymeleaf.png" },
      { name: "HTML", image: "/images/technologies/html.png" },
      { name: "CSS", image: "/images/technologies/css.png" },
      { name: "Javascript", image: "/images/technologies/javascript.png" },
    ],
    video: "3waglUa5Ako",
    github: "https://github.com/MuhammadUmar7831/eCafe",
    img: [
      "/images/projects/eCafe/1.png",
      "/images/projects/eCafe/2.png",
      "/images/projects/eCafe/3.png",
      "/images/projects/eCafe/4.png",
      "/images/projects/eCafe/5.png",
      "/images/projects/eCafe/6.png",
      "/images/projects/eCafe/7.png",
      "/images/projects/eCafe/8.png",
      "/images/projects/eCafe/9.png",
      "/images/projects/eCafe/10.png",
      "/images/projects/eCafe/11.png",
      "/images/projects/eCafe/12.png",
      "/images/projects/eCafe/13.png",
      "/images/projects/eCafe/14.png",
      "/images/projects/eCafe/15.png",
      "/images/projects/eCafe/16.png",
      "/images/projects/eCafe/17.png",
      "/images/projects/eCafe/18.png",
      "/images/projects/eCafe/19.png",
      "/images/projects/eCafe/20.png",
      "/images/projects/eCafe/21.png",
      "/images/projects/eCafe/22.png",
      "/images/projects/eCafe/23.png",
      "/images/projects/eCafe/24.png",
    ],
  },
  {
    id: 2,
    technologies: [
      { name: "MySql", image: "/images/technologies/mysql.png" },
      { name: "Express js", image: "/images/technologies/expressjs.png" },
      { name: "React", image: "/images/technologies/react.png" },
      { name: "Node js", image: "/images/technologies/nodejs.png" },
      { name: "Tailwindcss", image: "/images/technologies/tailwindcss.png" },
    ],
    video: "aVRNOz23oSM",
    github: "https://github.com/MuhammadUmar7831/Statistics-Application",
    img: [
      "/images/projects/statistics-app/1.png",
      "/images/projects/statistics-app/2.png",
      "/images/projects/statistics-app/3.png",
      "/images/projects/statistics-app/4.png",
      "/images/projects/statistics-app/5.png",
      "/images/projects/statistics-app/6.png",
      "/images/projects/statistics-app/7.png",
    ],
  },
  {
    id: 3,
    technologies: [
      { name: "Java", image: "/images/technologies/java.png" },
      { name: "SpringBoot", image: "/images/technologies/spring-boot.png" },
      { name: "Thymeleaf", image: "/images/technologies/thymeleaf.png" },
    ],
    video: "3waglUa5Ako",
    github: "https://github.com/MuhammadUmar7831/eCafe",
    liveDemo: "https://github.com/MuhammadUmar7831/eCafe",
    img: [
      "/images/projects/eCafe/1.png",
      "/images/projects/eCafe/2.png",
      "/images/projects/eCafe/3.png",
      "/images/projects/eCafe/4.png",
      "/images/projects/eCafe/5.png",
      "/images/projects/eCafe/6.png",
      "/images/projects/eCafe/7.png",
      "/images/projects/eCafe/8.png",
      "/images/projects/eCafe/9.png",
      "/images/projects/eCafe/10.png",
      "/images/projects/eCafe/11.png",
      "/images/projects/eCafe/12.png",
      "/images/projects/eCafe/13.png",
      "/images/projects/eCafe/14.png",
      "/images/projects/eCafe/15.png",
      "/images/projects/eCafe/16.png",
      "/images/projects/eCafe/17.png",
      "/images/projects/eCafe/18.png",
      "/images/projects/eCafe/19.png",
      "/images/projects/eCafe/20.png",
    ],
  },
];

export { details, projects };
